"""empty message

Revision ID: 05ee56596e3a
Revises: 814906fbcce9
Create Date: 2022-07-08 01:35:58.449375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ee56596e3a'
down_revision = '814906fbcce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletedoverhead', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('deletedstudentpayments', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deletedstudentpayments', 'reason')
    op.drop_column('deletedoverhead', 'reason')
    # ### end Alembic commands ###
