"""empty message

Revision ID: 06efd04cab9c
Revises: 40776c6d2bdc
Create Date: 2022-07-14 22:48:05.249800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06efd04cab9c'
down_revision = '40776c6d2bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deletedstaffsalaries', 'hello')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletedstaffsalaries', sa.Column('hello', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
