"""empty message

Revision ID: 106d90216640
Revises: 374d82f4b40c
Create Date: 2022-07-05 22:22:39.252075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106d90216640'
down_revision = '374d82f4b40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendancedays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.Column('calendar_day', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('activeness', sa.Integer(), nullable=True),
    sa.Column('dictionary', sa.Integer(), nullable=True),
    sa.Column('homework', sa.Integer(), nullable=True),
    sa.Column('average_ball', sa.Integer(), nullable=True),
    sa.Column('balance_per_day', sa.Integer(), nullable=True),
    sa.Column('salary_per_day', sa.Integer(), nullable=True),
    sa.Column('balance_with_discount', sa.Integer(), nullable=True),
    sa.Column('discount_per_day', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ),
    sa.ForeignKeyConstraint(['calendar_day'], ['calendarday.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendancedays')
    # ### end Alembic commands ###
