"""empty message

Revision ID: 1b2003abf918
Revises: d137aaed1ed7
Create Date: 2022-06-24 15:24:11.291805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2003abf918'
down_revision = 'd137aaed1ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'salary')
    # ### end Alembic commands ###
