"""empty message

Revision ID: 3a7519719759
Revises: 9844e7962a65
Create Date: 2022-07-04 15:45:20.730766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7519719759'
down_revision = '9844e7962a65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentdiscount', sa.Column('account_period_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'studentdiscount', 'accountingperiod', ['account_period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentdiscount', type_='foreignkey')
    op.drop_column('studentdiscount', 'account_period_id')
    # ### end Alembic commands ###
