"""empty message

Revision ID: 6fe827658389
Revises: 1b2003abf918
Create Date: 2022-06-24 15:35:41.948712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe827658389'
down_revision = '1b2003abf918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffsalary', sa.Column('staff_id', sa.Integer(), nullable=True))
    op.drop_constraint('staffsalary_stuff_id_fkey', 'staffsalary', type_='foreignkey')
    op.create_foreign_key(None, 'staffsalary', 'staff', ['staff_id'], ['id'])
    op.drop_column('staffsalary', 'stuff_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staffsalary', sa.Column('stuff_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staffsalary', type_='foreignkey')
    op.create_foreign_key('staffsalary_stuff_id_fkey', 'staffsalary', 'staff', ['stuff_id'], ['id'])
    op.drop_column('staffsalary', 'staff_id')
    # ### end Alembic commands ###
