"""empty message

Revision ID: 80b9a3dbae94
Revises: 9ecd966fd866
Create Date: 2022-07-05 19:56:03.546381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b9a3dbae94'
down_revision = '9ecd966fd866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountinginfo', sa.Column('all_discount', sa.Integer(), nullable=True))
    op.add_column('studentdiscount', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'studentdiscount', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentdiscount', type_='foreignkey')
    op.drop_column('studentdiscount', 'location_id')
    op.drop_column('accountinginfo', 'all_discount')
    # ### end Alembic commands ###
