"""empty message

Revision ID: 8b516eb37da7
Revises: a7577d1dbe2b
Create Date: 2022-07-06 21:57:22.475712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b516eb37da7'
down_revision = 'a7577d1dbe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deletedteachersalaries_attendance_history_id_fkey', 'deletedteachersalaries', type_='foreignkey')
    op.drop_column('deletedteachersalaries', 'attendance_history_id')
    op.drop_constraint('teachersalaries_attendance_history_id_fkey', 'teachersalaries', type_='foreignkey')
    op.drop_column('teachersalaries', 'attendance_history_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersalaries', sa.Column('attendance_history_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teachersalaries_attendance_history_id_fkey', 'teachersalaries', 'attendancehistoryteacher', ['attendance_history_id'], ['id'])
    op.add_column('deletedteachersalaries', sa.Column('attendance_history_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('deletedteachersalaries_attendance_history_id_fkey', 'deletedteachersalaries', 'attendancehistoryteacher', ['attendance_history_id'], ['id'])
    # ### end Alembic commands ###
