"""empty message

Revision ID: 948252e19200
Revises: 106d90216640
Create Date: 2022-07-05 23:00:28.351204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948252e19200'
down_revision = '106d90216640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studentpayments', sa.Column('payment', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('studentpayments', 'payment')
    # ### end Alembic commands ###
