"""empty message

Revision ID: 94fb059bb9b5
Revises: e2cf53561c0b
Create Date: 2022-07-10 15:18:04.644109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fb059bb9b5'
down_revision = 'e2cf53561c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teachersalaries_group_id_fkey', 'teachersalaries', type_='foreignkey')
    op.drop_column('teachersalaries', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersalaries', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('teachersalaries_group_id_fkey', 'teachersalaries', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###
