"""empty message

Revision ID: 9844e7962a65
Revises: a81d4bf9a39f
Create Date: 2022-07-04 15:39:33.728407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9844e7962a65'
down_revision = 'a81d4bf9a39f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountingperiod', sa.Column('year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accountingperiod', 'calendaryear', ['year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accountingperiod', type_='foreignkey')
    op.drop_column('accountingperiod', 'year_id')
    # ### end Alembic commands ###
