"""empty message

Revision ID: 9ecd966fd866
Revises: 3a7519719759
Create Date: 2022-07-04 16:19:51.127982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecd966fd866'
down_revision = '3a7519719759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accountingperiod', sa.Column('month_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accountingperiod', 'calendarmonth', ['month_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accountingperiod', type_='foreignkey')
    op.drop_column('accountingperiod', 'month_id')
    # ### end Alembic commands ###
