"""empty message

Revision ID: a7577d1dbe2b
Revises: 6bfa31e702db
Create Date: 2022-07-06 21:50:18.582173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7577d1dbe2b'
down_revision = '6bfa31e702db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletedteachersalaries', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('deletedteachersalaries', sa.Column('attendance_history_id', sa.Integer(), nullable=True))
    op.add_column('deletedteachersalaries', sa.Column('salary_location_id', sa.Integer(), nullable=True))
    op.drop_constraint('deletedteachersalaries_salary_id_fkey', 'deletedteachersalaries', type_='foreignkey')
    op.create_foreign_key(None, 'deletedteachersalaries', 'attendancehistoryteacher', ['attendance_history_id'], ['id'])
    op.create_foreign_key(None, 'deletedteachersalaries', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'deletedteachersalaries', 'teachersalary', ['salary_location_id'], ['id'])
    op.drop_column('deletedteachersalaries', 'salary_id')
    op.add_column('teachersalaries', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('teachersalaries', sa.Column('attendance_history_id', sa.Integer(), nullable=True))
    op.add_column('teachersalaries', sa.Column('salary_location_id', sa.Integer(), nullable=True))
    op.drop_constraint('teachersalaries_salary_id_fkey', 'teachersalaries', type_='foreignkey')
    op.create_foreign_key(None, 'teachersalaries', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'teachersalaries', 'attendancehistoryteacher', ['attendance_history_id'], ['id'])
    op.create_foreign_key(None, 'teachersalaries', 'teachersalary', ['salary_location_id'], ['id'])
    op.drop_column('teachersalaries', 'salary_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachersalaries', sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'teachersalaries', type_='foreignkey')
    op.drop_constraint(None, 'teachersalaries', type_='foreignkey')
    op.drop_constraint(None, 'teachersalaries', type_='foreignkey')
    op.create_foreign_key('teachersalaries_salary_id_fkey', 'teachersalaries', 'teachersalary', ['salary_id'], ['id'])
    op.drop_column('teachersalaries', 'salary_location_id')
    op.drop_column('teachersalaries', 'attendance_history_id')
    op.drop_column('teachersalaries', 'group_id')
    op.add_column('deletedteachersalaries', sa.Column('salary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deletedteachersalaries', type_='foreignkey')
    op.drop_constraint(None, 'deletedteachersalaries', type_='foreignkey')
    op.drop_constraint(None, 'deletedteachersalaries', type_='foreignkey')
    op.create_foreign_key('deletedteachersalaries_salary_id_fkey', 'deletedteachersalaries', 'teachersalary', ['salary_id'], ['id'])
    op.drop_column('deletedteachersalaries', 'salary_location_id')
    op.drop_column('deletedteachersalaries', 'attendance_history_id')
    op.drop_column('deletedteachersalaries', 'group_id')
    # ### end Alembic commands ###
