"""empty message

Revision ID: a81d4bf9a39f
Revises: 9151698ae1d5
Create Date: 2022-07-04 12:34:45.808900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a81d4bf9a39f'
down_revision = '9151698ae1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendarday', sa.Column('account_period_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendarday', 'accountingperiod', ['account_period_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendarday', type_='foreignkey')
    op.drop_column('calendarday', 'account_period_id')
    # ### end Alembic commands ###
