"""empty message

Revision ID: b29ed2f46bfc
Revises: 4da88bca2227
Create Date: 2022-07-08 01:32:16.845148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29ed2f46bfc'
down_revision = '4da88bca2227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletedstaffsalaries', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    op.add_column('deletedstudentpayments', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    op.add_column('deletedteachersalaries', sa.Column('deleted_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deletedteachersalaries', 'deleted_date')
    op.drop_column('deletedstudentpayments', 'deleted_date')
    op.drop_column('deletedstaffsalaries', 'deleted_date')
    # ### end Alembic commands ###
