"""empty message

Revision ID: e2cf53561c0b
Revises: 05ee56596e3a
Create Date: 2022-07-08 17:10:34.158764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cf53561c0b'
down_revision = '05ee56596e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deletedstaffsalaries', sa.Column('reason_deleted', sa.String(), nullable=True))
    op.add_column('deletedteachersalaries', sa.Column('reason_deleted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deletedteachersalaries', 'reason_deleted')
    op.drop_column('deletedstaffsalaries', 'reason_deleted')
    # ### end Alembic commands ###
